export const SELECTORS = {
  itemToInteractWith: 'Sauce Labs Backpack',
  addToCartButton: 'add-to-cart-sauce-labs-backpack',
  shoppingCartIcon: 'shopping-cart-icon',
  removeButton: 'remove-sauce-labs-backpack',
  continueShoppingButton: 'continue-shopping',
  yourCartTitle: 'Your Cart',
  productsTitle: 'Products',
  checkoutButton: 'checkout',
  firstNameField: 'firstName',
  lastNameField: 'lastName',
  postalCodeField: 'postalCode',
  continueButton: 'continue',
  cancelButton: 'cancel',
  errorMessage: 'error',
  finishButton: 'finish',
  thankYouTitle: 'Thank you for your order!',
  backButton: 'back-to-products',
  itemsInCartIcon: 'items-in-cart',
  itemNotToInteractWith: 'Sauce Labs Bike Light',
  loginPageTitle: 'Swag Labs',
  menuButton: 'Open Menu',
  logoutButton: 'Logout',
};
